version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: daimaru
      POSTGRES_PASSWORD: daimaru
      POSTGRES_DB: daimaru
    restart: always
    networks:
      - lesson
networks:
  lesson: